# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jdf_input_path', models.CharField(default='C:/APTApplication/Server/Inputs/JDFInput', max_length=200, verbose_name='JIF Input Folder')),
                ('reprint_path', models.CharField(default='C:/APTApplication/Server/Outputs/ReprintFiles', max_length=200, verbose_name='Reprint Folder')),
                ('proc_phase_path', models.CharField(default='C:/APTApplication/Server/Outputs/WIP', max_length=200, verbose_name='Processing Phase XML Folder')),
                ('jif_acks_path', models.CharField(default='C:/APTApplication/Server/Inputs/JIFAcks', max_length=200, verbose_name='JIF ACKs Folder')),
                ('idc_1_path', models.CharField(default='C:/APTApplication/IDC/IDC_1', max_length=200, verbose_name='IDC 1 Path')),
                ('idc_1_type', models.CharField(max_length=40, verbose_name='IDC 1 Device Type')),
                ('idc_1_time', models.IntegerField(verbose_name='IDC 1 Scans per hour')),
                ('idc_1_ps', models.CharField(default='sheet', max_length=5, verbose_name='IDC 1 piece or sheet')),
                ('idc_2_path', models.CharField(default='C:/APTApplication/IDC/IDC_2', max_length=200, verbose_name='IDC 2 Path')),
                ('idc_2_type', models.CharField(max_length=40, verbose_name='IDC 2 Device Type')),
                ('idc_2_time', models.IntegerField(verbose_name='IDC 2 Scans per hour')),
                ('idc_2_ps', models.CharField(default='sheet', max_length=5, verbose_name='IDC 2 piece or sheet')),
                ('idc_3_path', models.CharField(default='C:/APTApplication/IDC/IDC_3', max_length=200, verbose_name='IDC 3 Path')),
                ('idc_3_type', models.CharField(max_length=40, verbose_name='IDC 3 Device Type')),
                ('idc_3_time', models.IntegerField(verbose_name='IDC 3 Scans per hour')),
                ('idc_3_ps', models.CharField(default='piece', max_length=5, verbose_name='IDC 3 piece or sheet')),
                ('idc_4_path', models.CharField(default='C:/APTApplication/IDC/IDC_4', max_length=200, verbose_name='IDC 4 Path')),
                ('idc_4_type', models.CharField(max_length=40, verbose_name='IDC 4 Device Type')),
                ('idc_4_time', models.IntegerField(verbose_name='IDC 4 Scans per hour')),
                ('idc_4_ps', models.CharField(default='piece', max_length=5, verbose_name='IDC 4 piece or sheet')),
                ('td_multi_path', models.CharField(default='C:/APTApplication/IDC/TD', max_length=200, verbose_name='TD Input Path')),
                ('td_type', models.CharField(max_length=40, verbose_name='TD Device Type')),
            ],
        ),
        migrations.CreateModel(
            name='JIFTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(default='APTDemo', max_length=100)),
                ('job_prefix', models.CharField(max_length=3)),
                ('account_id', models.CharField(max_length=1000)),
                ('job_name', models.CharField(max_length=1000)),
                ('job_type', models.CharField(max_length=1000)),
                ('job_number', models.CharField(max_length=1000)),
                ('job_class', models.CharField(max_length=1000)),
                ('product_name', models.CharField(max_length=1000)),
                ('production_location', models.CharField(max_length=500)),
                ('envelope_id', models.CharField(max_length=1000)),
                ('stock_id', models.CharField(max_length=1000)),
                ('stock_type', models.CharField(max_length=1000)),
                ('user_info_1', models.CharField(max_length=1000)),
                ('user_info_2', models.CharField(max_length=1000)),
                ('user_info_3', models.CharField(max_length=1000)),
                ('user_info_4', models.CharField(max_length=1000)),
                ('user_info_5', models.CharField(max_length=1000)),
                ('contact_email', models.CharField(max_length=1000)),
                ('piece_range', models.CharField(max_length=100)),
                ('shift_1_operators', models.CharField(max_length=500)),
                ('shift_2_operators', models.CharField(max_length=500)),
                ('shift_3_operators', models.CharField(max_length=500)),
                ('template_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
