# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='democonfig',
            name='active_targets',
            field=models.CharField(default='icd_1, icd_2, icd_3, td', max_length=200, verbose_name='Active Targets'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='all_targets',
            field=models.CharField(default='icd_1, icd_2, icd_3, icd_4, icd_5, icd_6td', max_length=200, verbose_name='All Targets'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_1_multi',
            field=models.IntegerField(default=1, verbose_name='IDC Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_2_multi',
            field=models.IntegerField(default=0, verbose_name='IDC Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_3_multi',
            field=models.IntegerField(default=0, verbose_name='IDC Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_4_multi',
            field=models.IntegerField(default=0, verbose_name='IDC Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_5_multi',
            field=models.IntegerField(default=0, verbose_name='IDC Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_5_path',
            field=models.CharField(default='C:/APTApplication/IDC/idc_5', max_length=200, verbose_name='IDC 5 Path'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_5_ps',
            field=models.CharField(default='piece', max_length=5, verbose_name='IDC 5 piece or sheet'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_5_time',
            field=models.IntegerField(default=12000, verbose_name='IDC 5 Scans per hour'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_5_type',
            field=models.CharField(default='reprint', max_length=40, verbose_name='IDC 5 Device Type'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_6_multi',
            field=models.IntegerField(default=0, verbose_name='IDC Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_6_path',
            field=models.CharField(default='C:/APTApplication/IDC/idc_6', max_length=200, verbose_name='IDC 6 Path'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_6_ps',
            field=models.CharField(default='piece', max_length=5, verbose_name='IDC 6 piece or sheet'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_6_time',
            field=models.IntegerField(default=12000, verbose_name='IDC 6 Scans per hour'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='idc_6_type',
            field=models.CharField(default='reprint', max_length=40, verbose_name='IDC 6 Device Type'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='reprint_pool',
            field=models.CharField(default='icd_4, icd_5, icd_6', max_length=200, verbose_name='Reprint Pool'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='td_multi',
            field=models.IntegerField(default=0, verbose_name='TD Multi-step'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='td_path',
            field=models.CharField(default='C:/APTApplication/IDC/TD', max_length=200, verbose_name='TD Input Path'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='td_ps',
            field=models.CharField(default='piece', max_length=5, verbose_name='TD Piece or Sheet'),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='td_time',
            field=models.IntegerField(default=12000, verbose_name='TD Scans per hour'),
        ),
        migrations.AlterField(
            model_name='democonfig',
            name='idc_4_time',
            field=models.IntegerField(default=12000, verbose_name='IDC 4 Scans per hour'),
        ),
        migrations.AlterField(
            model_name='democonfig',
            name='idc_4_type',
            field=models.CharField(default='reprint', max_length=40, verbose_name='IDC 4 Device Type'),
        ),
        migrations.AlterField(
            model_name='democonfig',
            name='td_type',
            field=models.CharField(default='inserter', max_length=40, verbose_name='TD Device Type'),
        ),
    ]
